"""empty message

Revision ID: 39dba21a9581
Revises: c3cfd6bd0816
Create Date: 2024-04-08 20:20:50.737436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39dba21a9581'
down_revision = 'c3cfd6bd0816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_assembly_const')
    with op.batch_alter_table('assembly_const', schema=None) as batch_op:
        batch_op.drop_column('id')

    with op.batch_alter_table('polling_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_assembly_const_no', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_assembly_const_id', type_='foreignkey')
        batch_op.create_foreign_key('fk_assembly_const_no', 'assembly_const', ['fk_assembly_const_no'], ['ac_no'])
        batch_op.drop_column('fk_assembly_const_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_assembly_const_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_assembly_const_id', 'assembly_const', ['fk_assembly_const_id'], ['id'])
        batch_op.drop_column('fk_assembly_const_no')

    with op.batch_alter_table('assembly_const', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), nullable=False))

    op.create_table('_alembic_tmp_assembly_const',
    sa.Column('ac_no', sa.INTEGER(), nullable=False),
    sa.Column('ac_name', sa.VARCHAR(length=150), nullable=True),
    sa.Column('ac_category', sa.VARCHAR(length=150), nullable=True),
    sa.Column('remarks', sa.VARCHAR(length=150), nullable=True),
    sa.Column('state', sa.VARCHAR(length=150), nullable=True),
    sa.Column('district', sa.VARCHAR(length=150), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.UniqueConstraint('ac_no')
    )
    # ### end Alembic commands ###
