"""empty message

Revision ID: 48560d4c0afc
Revises: 82a835d4bc53
Create Date: 2024-04-12 12:28:08.112721

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48560d4c0afc'
down_revision = '82a835d4bc53'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_sangha', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('electors_male_sangha', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('electors_female_sangha', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('electors_other_sangha', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('electors_total_sangha', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling_station', schema=None) as batch_op:
        batch_op.drop_column('electors_total_sangha')
        batch_op.drop_column('electors_other_sangha')
        batch_op.drop_column('electors_female_sangha')
        batch_op.drop_column('electors_male_sangha')
        batch_op.drop_column('is_sangha')

    # ### end Alembic commands ###
