"""empty message

Revision ID: 6330cdd7519d
Revises: 821cd284e3db
Create Date: 2024-04-08 16:16:48.022583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6330cdd7519d'
down_revision = '821cd284e3db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling_station', schema=None) as batch_op:
        batch_op.drop_column('part_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('part_no', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
