"""empty message

Revision ID: 7abf6cebb45a
Revises: 39dba21a9581
Create Date: 2024-04-09 09:58:54.597194

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7abf6cebb45a'
down_revision = '39dba21a9581'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ac_election_officer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fk_assembly_const_no', sa.Integer(), nullable=True),
    sa.Column('designation', sa.String(length=150), nullable=True),
    sa.Column('designation_full', sa.String(length=150), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('office', sa.String(length=150), nullable=True),
    sa.Column('phone_no', sa.String(length=150), nullable=True),
    sa.Column('remarks', sa.String(length=150), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['fk_assembly_const_no'], ['assembly_const.ac_no'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ac_election_officer')
    # ### end Alembic commands ###
