"""empty message

Revision ID: 9ce55567e93e
Revises: c696189b82d3
Create Date: 2024-04-10 09:43:22.953110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ce55567e93e'
down_revision = 'c696189b82d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling_station', schema=None) as batch_op:
        batch_op.alter_column('ps_code',
               existing_type=sa.VARCHAR(length=12),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling_station', schema=None) as batch_op:
        batch_op.alter_column('ps_code',
               existing_type=sa.VARCHAR(length=12),
               nullable=False)

    # ### end Alembic commands ###
