"""empty message

Revision ID: c3cfd6bd0816
Revises: dc147b71f838
Create Date: 2024-04-08 20:14:36.101749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3cfd6bd0816'
down_revision = 'dc147b71f838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fk_assembly_const_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_assembly_const_id', 'assembly_const', ['fk_assembly_const_id'], ['id'])
        batch_op.drop_column('ac_no')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ac_no', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('fk_assembly_const_id')

    # ### end Alembic commands ###
