"""empty message

Revision ID: c696189b82d3
Revises: 7abf6cebb45a
Create Date: 2024-04-10 09:36:53.980765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c696189b82d3'
down_revision = '7abf6cebb45a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling_station', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ps_code', sa.String(length=12), nullable=False))
        batch_op.create_index(batch_op.f('ix_polling_station_ps_code'), ['ps_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('polling_station', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_polling_station_ps_code'))
        batch_op.drop_column('ps_code')

    # ### end Alembic commands ###
