"""empty message

Revision ID: d9f91a35a1e8
Revises: 412dca3f05a0
Create Date: 2024-04-08 09:49:05.513018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9f91a35a1e8'
down_revision = '412dca3f05a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('polling_station',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_no', sa.Integer(), nullable=False),
    sa.Column('part_name', sa.String(length=150), nullable=True),
    sa.Column('ps_no', sa.Integer(), nullable=False),
    sa.Column('ps_name', sa.String(length=150), nullable=True),
    sa.Column('ps_type', sa.String(length=150), nullable=True),
    sa.Column('ps_category', sa.String(length=150), nullable=True),
    sa.Column('location_type', sa.String(length=150), nullable=True),
    sa.Column('electors_male', sa.Integer(), nullable=True),
    sa.Column('electors_female', sa.Integer(), nullable=True),
    sa.Column('electors_other', sa.Integer(), nullable=True),
    sa.Column('electors_total', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('part_no'),
    sa.UniqueConstraint('ps_no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('polling_station')
    # ### end Alembic commands ###
